---
site_name: nokogiri.org
docs_dir: staging
markdown_extensions:
- codehilite
theme: readthedocs
nav:
- Overview: index.md
- Tutorials:
  - Installing Nokogiri: tutorials/installing_nokogiri.md
  - Parsing an HTML/XML document: tutorials/parsing_an_html_xml_document.md
  - Searching a XML/HTML document: tutorials/searching_a_xml_html_document.md
  - Modifying an HTML/XML document: tutorials/modifying_an_html_xml_document.md
  - Ensuring well-formed markup: tutorials/ensuring_well_formed_markup.md
- Getting Help: tutorials/getting_help.md
- Security: SECURITY.md
- License: LICENSE.md
- More Resources: tutorials/more_resources.md
