---
site_name: "Nokogiri"
site_url: https://nokogiri.org
repo_name: sparklemotion/nokogiri
repo_url: https://github.com/sparklemotion/nokogiri
edit_uri: ""
site_description: "The Official Tutorial Archive™ of Nokogiri®"
site_author: "Mike Dalessio"
copyright: "Copyright Ⓒ 2009-2020 Mike Dalessio"

docs_dir: staging
use_directory_urls: false

theme:
  name: material
  custom_dir: theme/extensions/material
  font:
    text: "Ubuntu"
    code: "Menlo"
  logo: "images/nokogiri-serif-white.svg"
  favicon: "images/nokogiri-serif-black.png"
  features: # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#configuration
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  palette:
    primary: black
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

extra_css:
  - "stylesheets/tidelift.css"

markdown_extensions:
  - "admonition"
  - "codehilite":
      "guess_lang": false
  - "toc":
      "permalink": true
      "toc_depth": 3
  - "footnotes" # https://python-markdown.github.io/extensions/footnotes/
  - "pymdownx.magiclink"

google_analytics:
  - "UA-1260604-8"
  - "nokogiri.org"

nav:
  - Readme: index.md
  - Support:
    - Installing Nokogiri: tutorials/installing_nokogiri.md
    - Nokogiri for Enterprise: tidelift-landing.md
    - Getting Help: tutorials/getting_help.md
    - Security: tutorials/security.md
    - More Resources: tutorials/more_resources.md
  - Tutorials:
    - Table of Contents: tutorials/toc.md
    - Parsing an HTML/XML document: tutorials/parsing_an_html_xml_document.md
    - Searching a XML/HTML document: tutorials/searching_a_xml_html_document.md
    - Modifying an HTML/XML document: tutorials/modifying_an_html_xml_document.md
    - Ensuring well-formed markup: tutorials/ensuring_well_formed_markup.md
  - About:
    - Changelog: CHANGELOG.md
    - Code of Conduct: CODE_OF_CONDUCT.md
    - Security: SECURITY.md
    - License: LICENSE.md
    - Dependencies: LICENSE-DEPENDENCIES.md
    - Roadmap: ROADMAP.md
  - RDoc: rdoc/index.html
