---
site_name: "Nokogiri"
site_url: https://nokogiri.org
repo_name: sparklemotion/nokogiri
repo_url: https://github.com/sparklemotion/nokogiri
edit_uri: ""
site_description: "The Official Tutorial Archive™ of Nokogiri®"
site_author: "Mike Dalessio"
copyright: "Copyright Ⓒ 2009-2021 Mike Dalessio"

docs_dir: staging
use_directory_urls: false

theme:
  name: material
  font:
    text: "Ubuntu"
    code: "Menlo"
  logo: "images/nokogiri-serif-white.svg"
  favicon: "images/nokogiri-serif-black.png"
  features: # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#configuration
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
#    - toc.integrate
  palette:
    primary: black
  icon:
    repo: fontawesome/brands/github

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sparklemotion/nokogiri.org
      name: sparklemotion/nokogiri.org

plugins:
  - search

extra_css:
  - "stylesheets/tidelift.css"
  - "stylesheets/custom.css"

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: 3
  - footnotes # https://python-markdown.github.io/extensions/footnotes/
  - pymdownx.magiclink
  - pymdownx.highlight
  - pymdownx.superfences

google_analytics:
  - "UA-1260604-8"
  - "nokogiri.org"

nav:
  - Home: index.md
  - API: rdoc/index.html
  - Support:
    - Installing Nokogiri: tutorials/installing_nokogiri.md
    - Nokogiri for Enterprise: tidelift-landing.md
    - Getting Help: tutorials/getting_help.md
    - Security: tutorials/security.md
    - More Resources: tutorials/more_resources.md
  - Tutorials:
    - Table of Contents: tutorials/toc.md
    - Parsing an HTML/XML document: tutorials/parsing_an_html_xml_document.md
    - Parsing an HTML5 document: tutorials/parsing_an_html5_document.md
    - Searching a XML/HTML document: tutorials/searching_a_xml_html_document.md
    - Modifying an HTML/XML document: tutorials/modifying_an_html_xml_document.md
    - Ensuring well-formed markup: tutorials/ensuring_well_formed_markup.md
  - Changelog: CHANGELOG.md
  - About:
    - Contributing: CONTRIBUTING.md
    - Code of Conduct: CODE_OF_CONDUCT.md
    - Security: SECURITY.md
    - License: LICENSE.md
    - Dependencies: LICENSE-DEPENDENCIES.md
    - Roadmap: ROADMAP.md
